# spring 总配置
spring:
   datasource:
      dynamic:
         druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
            # 连接池的配置信息
            # 初始化大小，最小，最大
            initial-size: 5
            min-idle: 5
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            # 打开PSCache，并且指定每个连接上PSCache的大小
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
            filters: stat,wall,slf4j
            # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
            connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
         datasource:
            master:
               url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
               username: root
               password: 123456
               driver-class-name: com.mysql.cj.jdbc.Driver
todo:
   # 持久化策略(localFile 本地文件, datasource 数据库, memory 仅内存这个不能持久化)
   persistence: localFile
   # 待办事项基础路径
   basePath: ./localFile/todolist
   # 待办事项基础文件名
   fileName: todoList.txt
   # 加载用户本地待办事项文件的时机
   # (init 在项目初始化的时候加载，会加载所有系统用户的待办事项, lazy 懒加载，只加载当前用户的待办事项)
   initFile: lazy
   # 导出文件的路径
   exportPath: ./localFile/export
   # 导出文件的类型(txt 文本文  excel 表格)
   exportType: excel
   # 导入文件的路径
   importPath: ./localFile/import
user:
   # 系统用户文件名
   fileName: todo-config.txt
   # 用户密码校验次数
   pwCheckNum: 5